# Generated by Django 3.2.6 on 2023-01-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenciaespecializada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaespecializada',
            name='respuesta',
            field=models.TextField(verbose_name='Respuesta'),
        ),
    ]
