# Generated by Django 3.2.6 on 2022-11-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombread', models.CharField(max_length=40, verbose_name='Nombre de la adquisición')),
            ],
        ),
    ]
