# Generated by Django 3.2.6 on 2023-01-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traducciondocumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traducciondocumento',
            name='adjunto1',
            field=models.FileField(null=True, upload_to='', verbose_name='Adjuntar'),
        ),
    ]
