# Generated by Django 3.2.6 on 2022-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('nombredocumento', models.CharField(max_length=40, verbose_name='Nombre del documento')),
                ('tipoprestamo', models.CharField(max_length=20, verbose_name='Tipo de prestamo')),
                ('fechaprestamo', models.DateField(verbose_name='Fecha de prestamo')),
                ('fecharecogida', models.DateField(verbose_name='Fecha de recogida')),
            ],
        ),
    ]
