# Generated by Django 3.2.6 on 2023-01-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteprestamo', '0002_rename_reporteprestamo_reporteprestamodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteprestamodocumento',
            name='tipoprestamo',
            field=models.CharField(choices=[('1', 'Interbibliotecario'), ('2', 'Individual')], default='1', max_length=40, verbose_name='Tipo de prestamo'),
        ),
    ]
