# Generated by Django 3.2.6 on 2023-01-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporteprestamo', '0003_alter_reporteprestamodocumento_tipoprestamo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportePrestamoDocumento',
            new_name='ReportePrestamo',
        ),
    ]
