# Generated by Django 3.2.6 on 2023-01-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteprestamo', '0004_rename_reporteprestamodocumento_reporteprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteprestamo',
            name='tipoprestamo',
            field=models.CharField(choices=[('Interbibliotecario', '1'), ('Individual', '2')], default='1', max_length=40, verbose_name='Tipo de prestamo'),
        ),
    ]
