# Generated by Django 3.2.6 on 2023-01-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteprestamo', '0005_alter_reporteprestamo_tipoprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteprestamo',
            name='tipoprestamo',
            field=models.CharField(choices=[('Interbibliotecario', 'Interbibliotecario'), ('Individual', 'Individual')], default='1', max_length=40, verbose_name='Tipo de prestamo'),
        ),
    ]
