# Generated by Django 3.2.6 on 2022-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Título')),
                ('resumen', models.TextField(verbose_name='Resumen')),
                ('texto', models.TextField(verbose_name='Descripción de la noticia')),
                ('autor', models.CharField(max_length=40, verbose_name='Autor')),
            ],
        ),
    ]
