# Generated by Django 3.2.6 on 2022-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformaUniversitaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
    ]
