# Generated by Django 3.2.6 on 2022-11-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformauniversitaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauniversitaria',
            name='url',
            field=models.CharField(max_length=40, verbose_name='Url'),
        ),
    ]
