# Generated by Django 3.2.6 on 2022-12-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformauniversitaria', '0002_alter_platformauniversitaria_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformaUniversitaria',
            new_name='PLATAFORMAU',
        ),
    ]
