# Generated by Django 3.2.6 on 2022-12-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliografia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliografia',
            new_name='BibliografiaEsp',
        ),
    ]
