# Generated by Django 3.2.6 on 2023-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=40, verbose_name='Nombre del usuario')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
            ],
        ),
    ]
